"use client";
import React,{useEffect,useMemo,useState}from"react";
import type{PersistedInteractiveJob}from"../lib/arc/interactive-job";
import{createArcFinalReceiptReader,FinalReceiptUnavailableError,readFinalReceipt,type FinalReceipt}from"../lib/arc/readFinalReceipt";
import{AddressDisplay,TransactionLink}from"./ui";
import{formatUsdc}from"./PayoutCalculationStep";

export function FinalSettlementReceipt({job}:{job:PersistedInteractiveJob}){const reader=useMemo(createArcFinalReceiptReader,[]),[receipt,setReceipt]=useState<FinalReceipt|null>(null),[state,setState]=useState<"loading"|"not-settled"|"error">("loading");useEffect(()=>{let active=true;setReceipt(null);setState("loading");void readFinalReceipt(reader,job).then(value=>{if(active)setReceipt(value)}).catch(cause=>{if(active)setState(cause instanceof FinalReceiptUnavailableError&&cause.reason==="not-settled"?"not-settled":"error")});return()=>{active=false}},[job,reader]);return <section className="execution-panel panel" aria-live="polite"><header className="execution-step"><span>08 / FINAL RECEIPT</span><p>Final settlement receipt verified from live Arc state.</p></header>{receipt?<FinalReceiptDetails receipt={receipt}/>:<FinalReceiptUnavailable state={state}/>}</section>}
export function FinalReceiptUnavailable({state}:{state:"loading"|"not-settled"|"error"}){return <div className={state==="error"?"state-card error":"state-card"} role={state==="error"?"alert":undefined}><strong>{state==="loading"?"Verifying final settlement on Arc":state==="not-settled"?"Receipt pending":"Receipt verification unavailable"}</strong><span>{state==="loading"?"Reading authoritative job and settlement state.":state==="not-settled"?"Final receipt becomes available after the job is settled on Arc.":"Live Arc verification failed. A cached receipt will not be shown."}</span></div>}
export function FinalReceiptDetails({receipt}:{receipt:FinalReceipt}){const h=receipt.history;return <><div className="execution-confirmed"><strong>SETTLEMENT COMPLETE</strong></div><dl className="execution-metadata execution-policy"><div><dt>Job</dt><dd>#{receipt.jobId.toString()}</dd></div><div><dt>Network</dt><dd>Arc Testnet</dd></div><div><dt>Task</dt><dd>Supplier data extraction</dd></div><div><dt>Scorer</dt><dd>ExactMatchScorer</dd></div>{receipt.matchCount!==null&&<div><dt>Result</dt><dd>{receipt.matchCount} / 50 matches</dd></div>}<div><dt>Quality</dt><dd>92% · 9200 BPS</dd></div><div><dt>Payout Rate</dt><dd>85% · 8500 BPS</dd></div><div><dt>Budget</dt><dd>{formatUsdc(receipt.budget)} USDC</dd></div><div><dt>Provider Paid</dt><dd>{formatUsdc(receipt.providerPayment)} USDC</dd></div><div><dt>Client Refunded</dt><dd>{formatUsdc(receipt.clientRefund)} USDC</dd></div><div><dt>Client</dt><dd><AddressDisplay address={receipt.client} href/></dd></div><div><dt>Provider</dt><dd><AddressDisplay address={receipt.provider} href/></dd></div><div><dt>Expected Commitment</dt><dd className="address" title={receipt.expectedCommitment}>{short(receipt.expectedCommitment)}</dd></div><div><dt>Result Commitment</dt><dd className="address" title={receipt.resultCommitment}>{short(receipt.resultCommitment)}</dd></div><div><dt>Settlement Transaction</dt><dd>{receipt.settlementTransactionHash?<TransactionLink hash={receipt.settlementTransactionHash}/>:"Unavailable"}</dd></div></dl><div className="execution-metadata execution-policy" aria-label="Provider History"><div><dt>Measured Jobs</dt><dd>{h.measuredJobs.toString()}</dd></div><div><dt>Average Quality</dt><dd>{h.averageQualityBps.toString()} BPS</dd></div><div><dt>Completed Jobs</dt><dd>{h.completedJobs.toString()}</dd></div><div><dt>Submission Defaults</dt><dd>{h.submissionDefaults.toString()}</dd></div></div>{receipt.settlementTransactionHash&&<p><TransactionLink hash={receipt.settlementTransactionHash} label="View Settlement on Arc"/></p>}<p className="execution-confirmed"><span aria-hidden>✓</span> Verified on Arc</p></>}
function short(value:string){return`${value.slice(0,10)}…${value.slice(-6)}`}
