import React from "react";
import Link from "next/link";
import type { DemoJob, JobStatus } from "../data/types";
import { demo } from "../data/demo";
import { explorerLinks, formatAddress, formatBps, formatUsdc } from "../lib/ui/format";
import type { ArcReadResult } from "../lib/arc/read-model";
export function NetworkBadge(){return <span className="network-badge"><span className="pulse"/>Arc Testnet</span>}
export function StatusBadge({status}:{status:JobStatus}){return <span className={`status status-${status.toLowerCase()}`}><span aria-hidden>●</span>{status}</span>}
export function MetricCard({label,value,detail,accent=""}:{label:string;value:string;detail:string;accent?:string}){return <article className={`metric-card ${accent}`}><span>{label}</span><strong>{value}</strong><small>{detail}</small></article>}
export function AddressDisplay({address,href=false}:{address:string;href?:boolean}){const text=formatAddress(address);return href?<a className="address" href={explorerLinks.address(address)} target="_blank" rel="noreferrer" title={address} aria-label={`View address ${address} on ArcScan`}>{text}<span aria-hidden>↗</span></a>:<span className="address" title={address} data-address={address}>{text}</span>}
export function TransactionLink({hash,label}:{hash:string;label?:string}){return <a className="tx-link" href={explorerLinks.transaction(hash)} target="_blank" rel="noreferrer" title={hash}>{label??formatAddress(hash,8,6)}<span aria-hidden>↗</span></a>}
export function PageHeader({eyebrow,title,description,compact=false,aside}:{eyebrow:string;title:string;description:string;compact?:boolean;aside?:React.ReactNode}){return <header className={`page-header ${compact?"compact":""}`}><div><div className="section-kicker">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{aside}</header>}
export function QualityScore({correct,total,qualityBps}:{correct:number;total:number;qualityBps:number}){return <div className="quality-score"><div className="score-ring" style={{"--score":`${qualityBps/100}%`} as React.CSSProperties}><strong>{formatBps(qualityBps)}</strong><span>measured</span></div><div><span className="label">Exact-match score</span><strong>{correct}/{total} answers</strong><small>{qualityBps} bps = {formatBps(qualityBps)}</small></div></div>}
export function PayoutBreakdown({job}:{job:DemoJob}){return <div className="payout-breakdown"><div><span>Payout rate</span><strong>{formatBps(job.payoutBps)}</strong></div><div><span>Provider payment</span><strong>{formatUsdc(job.providerPaymentUsdc)}</strong></div><div><span>Client refund</span><strong>{formatUsdc(job.clientRefundUsdc)}</strong></div><div><span>Escrow balance</span><strong>{formatUsdc(job.escrowBalanceUsdc)}</strong></div></div>}
export const lifecycle=["Funded","Accepted","Submitted","Scored","Settled"] as const;
export function JobLifecycle({job}:{job:DemoJob}){return <ol className="timeline" aria-label="Completed job lifecycle">{lifecycle.map((step,index)=><li key={step} className="complete"><span className="timeline-marker">✓</span><div><strong>{step}</strong><small>{["Client policy funded 1 USDC","Provider accepted profitable work","Result commitment became immutable","46/50 answers matched exactly","USDC paid and history updated"][index]}</small></div>{job.transactions[index]&&<TransactionLink hash={job.transactions[index].hash} label={job.transactions[index].timestamp}/>}</li>)}</ol>}
export function EmptyState(){return <div className="state-card"><strong>No jobs found</strong><span>Jobs matching this view will appear here.</span></div>}
export function ErrorState(){return <div className="state-card error" role="alert"><strong>Unable to display data</strong><span>The static demo data could not be loaded.</span></div>}
export function LoadingSkeleton(){return <div className="skeleton" aria-label="Loading content"><i/><i/><i/></div>}
export function PayoutCurve(){return <div className="curve"><div className="curve-track"><span className="curve-line"/><span className="curve-score" style={{left:"55%"}}><b>92%</b></span></div><div className="curve-points">{demo.verifiedJob.payoutCurve.map(point=><div key={point.metricBps}><strong>{formatBps(point.metricBps)}</strong><span>{formatBps(point.payoutBps)} payout</span></div>)}</div></div>}
export function JobLink({id}:{id:number}){return <Link className="job-link" href={`/jobs/${id}`}>Job #{id}</Link>}
export function DataReadStatus({data}:{data:ArcReadResult}){const live=data.source==="LIVE";return <aside className={`read-status ${live?"live":"fallback"}`} aria-label="Arc read status"><div><span className="read-source">{live?"Live on Arc":"Verified fallback"}</span><span className="static-label">Read-only Arc data</span><span className={`rpc-state rpc-${data.rpcState.toLowerCase().replace(" ","-")}`}>RPC: {data.rpcState}</span></div><small>Last checked <time dateTime={data.fetchedAt}>{new Date(data.fetchedAt).toLocaleString("en-GB",{timeZone:"UTC"})} UTC</time></small><a className="refresh-read" href="?refresh=1">Refresh read</a>{data.warnings.map(warning=><p key={warning} role="alert">{warning}</p>)}</aside>}
