import assert from "node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import React from"react";import{renderToStaticMarkup}from"react-dom/server";import{encodeEventTopics,type Address,type Hash,type Hex}from"viem";
import{ProviderAcceptStep}from"../src/components/ProviderAcceptStep";import{veriqEscrowAcceptAbi}from"../src/lib/arc/abi/veriq-escrow-accept";import{buildInteractiveJobParameters,INTERACTIVE_PROVIDER_ADDRESS,type PersistedInteractiveJob}from"../src/lib/arc/interactive-job";import{ACCEPTANCE_SAFETY_BUFFER_SECONDS,createBrowserAcceptAdapter,executeAcceptJob,reconcileRecoveredJob,type AcceptanceJob,type AcceptJobAdapter}from"../src/lib/wallet/acceptFundedJob";import type{InjectedProvider}from"../src/lib/wallet/injectedWallet";
const CLIENT="0x333C8bc19741f2Ed0C57d0C028Bff7c076B28E5C"as Address,PROVIDER=INTERACTIVE_PROVIDER_ADDRESS,OTHER="0x2222222222222222222222222222222222222222"as Address,HASH=`0x${"c".repeat(64)}`as Hash;
function state():PersistedInteractiveJob{const p=buildInteractiveJobParameters(2_000_000_000n);return{version:1,chainId:5_042_002,jobId:"2",client:CLIENT,provider:PROVIDER,createTransactionHash:`0x${"b".repeat(64)}`,taskSpecHash:p.taskSpecHash,canonicalizationVersionHash:p.canonicalizationVersionHash,metricPoints:p.metricPoints.map(String),payoutBps:p.payoutBps.map(String),acceptanceDeadline:p.acceptanceDeadline.toString(),submissionDeadline:p.submissionDeadline.toString(),revealDeadline:p.revealDeadline.toString(),expectedAnswerCommitment:p.expectedAnswerCommitment,expectedAnswerHashes:p.expectedAnswerHashes,budget:"1000000",status:"Funded"}}
class Fake implements AcceptJobAdapter{now=2_000_000_000n;live:AcceptanceJob={client:CLIENT,provider:PROVIDER,budget:1_000_000n,acceptanceDeadline:this.now+3600n,status:1};revalidations=0;accepts=0;event={jobId:2n,provider:PROVIDER};receiptFails=false;acceptError:Error|null=null;async revalidate(){this.revalidations++}async readJob(){return this.live}async latestBlockTimestamp(){return this.now}async acceptJob(_p:Address,_id:bigint){this.accepts++;if(this.acceptError)throw this.acceptError;this.live={...this.live,status:2};return HASH}async waitForSuccessfulReceipt(){if(this.receiptFails)throw new Error("reverted");return{logs:[]}}decodeJobAccepted(){return this.event}}
test("only assigned provider can accept",async()=>{for(const wallet of[CLIENT,OTHER]){const f=new Fake();await assert.rejects(executeAcceptJob(f,state(),wallet),/assigned provider/);assert.equal(f.accepts,0)}});
test("60-second safety buffer blocks unsafe acceptance",async()=>{const f=new Fake();f.live.acceptanceDeadline=f.now+ACCEPTANCE_SAFETY_BUFFER_SECONDS-1n;await assert.rejects(executeAcceptJob(f,state(),PROVIDER),/too close/);assert.equal(f.accepts,0)});
test("acceptance revalidates twice and confirms Accepted readback",async()=>{const f=new Fake();const result=await executeAcceptJob(f,state(),PROVIDER);assert.equal(f.revalidations,2);assert.equal(result.status,"Accepted");assert.equal(result.acceptanceTransactionHash,HASH);assert.equal(result.confirmedProvider,PROVIDER)});
test("receipt and event mismatches fail",async()=>{const a=new Fake();a.receiptFails=true;await assert.rejects(executeAcceptJob(a,state(),PROVIDER),/reverted/);const b=new Fake();b.event={jobId:3n,provider:PROVIDER};await assert.rejects(executeAcceptJob(b,state(),PROVIDER),/job ID mismatch/);const c=new Fake();c.event={jobId:2n,provider:OTHER};await assert.rejects(executeAcceptJob(c,state(),PROVIDER),/provider mismatch/)});
test("simulation or wallet rejection propagates",async()=>{const f=new Fake();f.acceptError=new Error("User rejected 4001");await assert.rejects(executeAcceptJob(f,state(),PROVIDER),/rejected/)});
test("Arc Accepted state upgrades persistence without fabricating hash",()=>{const s=state();const recovered=reconcileRecoveredJob(s,{client:CLIENT,provider:PROVIDER,budget:1_000_000n,acceptanceDeadline:9n,status:2});assert.equal(recovered.status,"Accepted");assert.equal(recovered.acceptanceTransactionHash,null);assert.equal(recovered.confirmedProvider,PROVIDER)});
test("JobAccepted browser decoder validates indexed data",()=>{const adapter=createBrowserAcceptAdapter({request:async()=>null}as unknown as InjectedProvider);const topics=encodeEventTopics({abi:veriqEscrowAcceptAbi,eventName:"JobAccepted",args:{jobId:2n,provider:PROVIDER}});assert.deepEqual(adapter.decodeJobAccepted([{data:"0x",topics:topics as readonly Hex[]}]),{jobId:2n,provider:PROVIDER})});
test("client, provider, unrelated, and accepted UI states are explicit",()=>{const p={request:async()=>null}as unknown as InjectedProvider;const clientHtml=renderToStaticMarkup(<ProviderAcceptStep account={CLIENT} provider={p} job={state()} onAccepted={()=>{}}/>);assert.match(clientHtml,/Switch to the assigned provider wallet/);assert.doesNotMatch(clientHtml,/>Accept Job</);const providerHtml=renderToStaticMarkup(<ProviderAcceptStep account={PROVIDER} provider={p} job={state()} onAccepted={()=>{}}/>);assert.match(providerHtml,/Checking acceptance deadline/);assert.match(readFileSync("src/components/ProviderAcceptStep.tsx","utf8"),/"Accept Job"/);const otherHtml=renderToStaticMarkup(<ProviderAcceptStep account={OTHER} provider={p} job={state()} onAccepted={()=>{}}/>);assert.match(otherHtml,/does not match/);const accepted={...state(),status:"Accepted"as const,acceptanceTransactionHash:null};const acceptedHtml=renderToStaticMarkup(<ProviderAcceptStep account={PROVIDER} provider={p} job={accepted} onAccepted={()=>{}}/>);assert.match(acceptedHtml,/Unavailable/);assert.match(acceptedHtml,/Confirmed on Arc/)});
test("only new lifecycle write surface is acceptJob",()=>{const abi=readFileSync("src/lib/arc/abi/veriq-escrow-accept.ts","utf8");const source=[abi,readFileSync("src/lib/wallet/acceptFundedJob.ts","utf8")].join("\n");assert.match(abi,/name: "acceptJob"/);assert.doesNotMatch(source,/submitResultCommitment|revealAndScore|settle|ProviderHistory|writeContract.*acceptJob.*writeContract/s)});
