import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { ARC_TESTNET_CHAIN_ID, ARC_TESTNET_RPC_URL, ARC_USDC_ADDRESS, assertOfficialArcRpc } from "../src/lib/arc/chain.ts";
import { ARC_READ_REVALIDATE_SECONDS, ARC_READ_TIMEOUT_MS, VERIFIED_BUDGET, VERIFIED_ESCROW_ADDRESS, VERIFIED_PROVIDER, formatUsdcBaseUnits, normalizeStatus, requireBps } from "../src/lib/arc/read-model.ts";
import { classifyReadFailure, readArcWithFallback, readLiveArcState, verifiedFallback, type ArcContractReadClient } from "../src/lib/arc/read-core.ts";
import { resolveServerRead } from "../src/lib/arc/read-server-policy.ts";
import { mockUsdcReadAbi } from "../src/lib/arc/abi/mock-usdc-read.ts";
import { veriqEscrowReadAbi } from "../src/lib/arc/abi/veriq-escrow-read.ts";
import { OverviewView, JobsView, JobDetailsView, ProviderHistoryView } from "../src/components/live-pages.tsx";
import { formatBps } from "../src/lib/ui/format.ts";

const artifacts={veriqEscrow:{abi:veriqEscrowReadAbi},mockUsdc:{abi:mockUsdcReadAbi}};
const clientAddress="0xd55692a56f3ff2fEC95b0F4547C98D140469D95C" as const;
const expectedCommitment=`0x${"11".repeat(32)}` as const;
const providerCommitment=`0x${"22".repeat(32)}` as const;
type Overrides={chainId?:number;code?:`0x${string}`|undefined;job?:readonly unknown[];settlement?:readonly unknown[];history?:readonly unknown[];token?:string;reject?:Error;balances?:Record<string,bigint>};
function mockClient(o:Overrides={}):ArcContractReadClient{const job=o.job??[clientAddress,VERIFIED_PROVIDER,1_000_000n,"0x"+"33".repeat(32),expectedCommitment,"0x"+"44".repeat(32),1785900000n,1785903600n,1785907200n,5n];const settlement=o.settlement??[9200n,8500n,850000n,150000n,5n];const history=o.history??[1n,9200n,9200n,1n,0n];return {getChainId:async()=>{if(o.reject)throw o.reject;return o.chainId??ARC_TESTNET_CHAIN_ID},getBlockNumber:async()=>123456n,getBytecode:async()=>o.code===undefined?"0x1234":o.code,readContract:async({functionName,args})=>{if(functionName==="escrowToken")return o.token??ARC_USDC_ADDRESS;if(functionName==="getJob")return job;if(functionName==="getSettlementResult")return settlement;if(functionName==="getResultCommitment")return providerCommitment;if(functionName==="getProviderHistory")return history;if(functionName==="balanceOf")return o.balances?.[String(args?.[0]).toLowerCase()]??0n;throw new Error(`Unexpected read ${functionName}`)}}}
const live=()=>readLiveArcState(mockClient(),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi,new Date("2026-08-05T12:00:00Z"));
const html=(node:React.ReactNode)=>renderToStaticMarkup(React.createElement(React.Fragment,null,node));

test("Arc live reader uses chain ID 5042002",()=>assert.equal(ARC_TESTNET_CHAIN_ID,5042002));
test("Arc live reader uses official dot-io RPC",()=>assert.equal(ARC_TESTNET_RPC_URL,"https://rpc.testnet.arc.io"));
test("Arc live reader rejects obsolete dot-network RPC",()=>assert.throws(()=>assertOfficialArcRpc("https://rpc.testnet.arc.network")));
test("VeriqEscrow address matches verified deployment",()=>assert.equal(VERIFIED_ESCROW_ADDRESS,"0xd7bc6d86afcf8f4fdc02e990222951978afd311b"));
test("escrow token must equal official Arc USDC",async()=>assert.equal((await readArcWithFallback(mockClient({token:"0x1111111111111111111111111111111111111111"}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).source,"VERIFIED_FALLBACK"));
test("Job #1 live read normalizes client and provider addresses",async()=>{const r=await live();assert.equal(r.job.client,clientAddress);assert.equal(r.job.provider,VERIFIED_PROVIDER)});
test("Job #1 live read normalizes one USDC budget",async()=>assert.equal((await live()).job.budget,1_000_000n));
test("status enum Settled maps correctly",()=>assert.equal(normalizeStatus(5n),"Settled"));
test("unknown status enum is rejected",()=>assert.throws(()=>normalizeStatus(9n),/Unknown/));
test("qualityBps 9200 formats as 92 percent",()=>assert.equal(formatBps(9200),"92%"));
test("payoutBps 8500 formats as 85 percent",()=>assert.equal(formatBps(8500),"85%"));
test("provider payment 850000 formats as 0.85 USDC",()=>assert.equal(formatUsdcBaseUnits(850000n),"0.85"));
test("client refund 150000 formats as 0.15 USDC",()=>assert.equal(formatUsdcBaseUnits(150000n),"0.15"));
test("provider payment plus refund must equal budget",async()=>assert.equal((await readArcWithFallback(mockClient({settlement:[9200n,8500n,800000n,150000n,5n]}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).source,"VERIFIED_FALLBACK"));
test("escrow zero balance validates settled accounting",async()=>assert.equal((await live()).warnings.length,0));
test("provider history live values normalize correctly",async()=>assert.deepEqual((await live()).providerHistory,{measuredJobs:1n,cumulativeQualityBps:9200n,averageQualityBps:9200n,completedJobs:1n,submissionDefaults:0n}));
test("basis-point values outside range are rejected",()=>assert.throws(()=>requireBps("quality",10001n)));
test("missing job produces verified fallback",async()=>assert.equal((await readArcWithFallback(mockClient({job:["0x0000000000000000000000000000000000000000","0x0000000000000000000000000000000000000000",0n,expectedCommitment,expectedCommitment,expectedCommitment,0n,0n,0n,0n]}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).source,"VERIFIED_FALLBACK"));
test("RPC timeout produces verified fallback",async()=>assert.equal((await readArcWithFallback(mockClient({reject:new Error("timeout")}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).rpcState,"Unavailable"));
test("wrong chain produces fallback with warning",async()=>assert.match((await readArcWithFallback(mockClient({chainId:1}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).warnings[0],/wrong chain/i));
test("missing escrow bytecode produces verified fallback",async()=>assert.match((await readArcWithFallback(mockClient({code:"0x"}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).warnings[0],/bytecode/i));
test("unexpected provider produces integrity warning",async()=>assert.match((await readLiveArcState(mockClient({job:[clientAddress,"0x1111111111111111111111111111111111111111",1_000_000n,expectedCommitment,expectedCommitment,expectedCommitment,1n,2n,3n,5n]}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).warnings.join(),/Provider mismatch/));
test("unexpected budget produces integrity warning",async()=>assert.match((await readLiveArcState(mockClient({job:[clientAddress,VERIFIED_PROVIDER,2_000_000n,expectedCommitment,expectedCommitment,expectedCommitment,1n,2n,3n,5n],settlement:[9200n,8500n,1_700_000n,300_000n,5n]}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).warnings.join(),/Budget mismatch/));
test("unexpected quality produces integrity warning",async()=>assert.match((await readLiveArcState(mockClient({settlement:[9000n,8500n,850000n,150000n,5n]}),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi)).warnings.join(),/Quality mismatch/));
test("live result is labeled LIVE",async()=>assert.equal((await live()).source,"LIVE"));
test("fallback result is labeled VERIFIED_FALLBACK",()=>assert.equal(verifiedFallback().source,"VERIFIED_FALLBACK"));
test("fallback values exactly match Milestone 13B",()=>{const r=verifiedFallback();assert.deepEqual([r.job.budget,r.job.qualityBps,r.job.payoutBps,r.job.providerPayment,r.job.clientRefund,r.balances.escrow],[VERIFIED_BUDGET,9200,8500,850000n,150000n,0n])});
test("Overview renders live-source badge",async()=>assert.match(html(<OverviewView data={await live()}/>),/Live on Arc/));
test("Overview renders fallback warning when RPC fails",()=>assert.match(html(<OverviewView data={verifiedFallback()}/>),/Arc RPC is temporarily unavailable/));
test("Job #1 renders live status and accounting",async()=>{const value=html(<JobDetailsView params={{id:"1"}} data={await live()}/>);assert.match(value,/Settled/);assert.match(value,/0\.85 USDC/)});
test("Jobs page keeps non-live records labeled Static demo",async()=>assert.match(html(<JobsView data={await live()}/>),/Static demo/));
test("Provider History renders live counters",async()=>assert.match(html(<ProviderHistoryView data={await live()}/>),/Cumulative quality[\s\S]*9200 bps/));
test("transaction references remain verified static references",async()=>assert.match(html(<JobDetailsView params={{id:"1"}} data={await live()}/>),/Verified Milestone 13B transaction references/));
test("no wallet-connect control is rendered",async()=>assert.doesNotMatch(html(<OverviewView data={await live()}/>),/connect wallet|walletconnect|metamask/i));
test("no contract-write function is imported into frontend routes",()=>{for(const file of ["app/page.tsx","app/jobs/page.tsx","app/jobs/[id]/page.tsx","app/provider-history/page.tsx"])assert.doesNotMatch(readFileSync(file,"utf8"),/writeContract|sendTransaction|WalletClient|sendSimulatedWrite/)});
test("client source contains no private-key environment names",()=>{for(const file of ["src/components/ui.tsx","src/components/AppShell.tsx","app/page.tsx"])assert.doesNotMatch(readFileSync(file,"utf8"),/ARC_(DEPLOYER|CLIENT|PROVIDER)_PRIVATE_KEY/)});
test("input objects are not mutated",async()=>{const o=Object.freeze({settlement:Object.freeze([9200n,8500n,850000n,150000n,5n])});await readLiveArcState(mockClient(o),artifacts.veriqEscrow.abi,artifacts.mockUsdc.abi);assert.equal(o.settlement[0],9200n)});
test("read caching revalidation is controlled",()=>assert.ok(ARC_READ_REVALIDATE_SECONDS>=30&&ARC_READ_REVALIDATE_SECONDS<=60));
test("manual refresh requests a fresh server read",async()=>{const value=html(<OverviewView data={await live()}/>);assert.match(value,/href="\?refresh=1"/);const page=readFileSync("app/page.tsx","utf8");assert.match(page,/refresh===?"1"|refresh\s*===\s*"1"/);assert.doesNotMatch(page,/writeContract|sendTransaction|WalletClient/)});
test("error output does not expose raw secrets or environment values",()=>{const r=verifiedFallback(`failed ${"0x"+"ab".repeat(32)}`);assert.doesNotMatch(r.warnings[0],/abababab/);assert.ok(r.warnings[0].length<=240)});
test("server and CLI share the same bounded request timeout",()=>{assert.equal(ARC_READ_TIMEOUT_MS,15_000);for(const file of ["src/lib/arc/read-server.ts","src/lib/arc/read-live-cli.ts"])assert.match(readFileSync(file,"utf8"),/ARC_READ_TIMEOUT_MS/)});
test("successful Next server read returns LIVE",async()=>assert.equal((await resolveServerRead({}, {readCached:live,readFresh:live,fallback:()=>verifiedFallback()})).source,"LIVE"));
test("failed reads are not retained and a subsequent success replaces fallback",async()=>{let calls=0;const readCached=async()=>{calls++;if(calls===1)throw new Error("timeout");return live()};const dependencies={readCached,readFresh:live,fallback:()=>verifiedFallback()};assert.equal((await resolveServerRead({},dependencies)).source,"VERIFIED_FALLBACK");assert.equal((await resolveServerRead({},dependencies)).source,"LIVE");assert.equal(calls,2)});
test("manual refresh bypasses the cached reader",async()=>{let cached=0,fresh=0;const result=await resolveServerRead({fresh:true},{readCached:async()=>{cached++;return verifiedFallback()},readFresh:async()=>{fresh++;return live()},fallback:()=>verifiedFallback()});assert.equal(result.source,"LIVE");assert.deepEqual([cached,fresh],[0,1])});
test("server cache stores only validated live reads",()=>{const source=readFileSync("src/lib/arc/read-server.ts","utf8");assert.match(source,/unstable_cache\(fetchArcReadStateSerialized/);assert.match(source,/fetchArcReadStateSerialized[\s\S]*readLiveArcState/);assert.doesNotMatch(source,/fetchArcReadStateSerialized[\s\S]{0,300}readArcWithFallback/)});
test("fallback failures receive sanitized categories",()=>{assert.equal(classifyReadFailure(new Error("request timed out")).category,"timeout");const diagnostic=classifyReadFailure(new Error("fetch failed: authorization=secret-value https://rpc.invalid 0x"+"ab".repeat(32)));assert.equal(diagnostic.category,"connection");assert.doesNotMatch(diagnostic.message,/secret-value|rpc\.invalid|abababab/)});
test("Arc server and CLI import deployment-safe shared ABIs",()=>{for(const file of ["src/lib/arc/read-server.ts","src/lib/arc/read-live-cli.ts"]){const source=readFileSync(file,"utf8");assert.match(source,/abi\/mock-usdc-read/);assert.match(source,/abi\/veriq-escrow-read/);assert.doesNotMatch(source,/contracts\/artifacts|loadContractArtifacts/)}});
test("Arc runtime code has no Foundry artifact or parent-directory dependency",()=>{for(const file of ["src/lib/arc/read-core.ts","src/lib/arc/read-server.ts","src/lib/arc/read-live-cli.ts","src/lib/arc/abi/mock-usdc-read.ts","src/lib/arc/abi/veriq-escrow-read.ts"]){const source=readFileSync(file,"utf8");assert.doesNotMatch(source,/contracts[\\/]out|process\.cwd|readFileSync|node:fs|\.\.\/\.\.\/\.\./)}});
test("MockUSDC read ABI contains decimals and balanceOf",()=>assert.deepEqual(mockUsdcReadAbi.map(item=>item.name),["decimals","balanceOf"]));
test("VeriqEscrow read ABI exactly covers Job #1 reads",()=>assert.deepEqual(veriqEscrowReadAbi.map(item=>item.name),["escrowToken","getJob","getSettlementResult","getResultCommitment","getProviderHistory"]));
test("deployment-safe ABIs contain read-only functions only",()=>{for(const item of [...mockUsdcReadAbi,...veriqEscrowReadAbi])assert.equal(item.stateMutability,"view")});
test("missing ABI artifact is a configuration failure, not RPC unavailable",()=>{const diagnostic=classifyReadFailure(new Error("ENOENT: no such file or directory, open '/var/task/contracts/out/MockUSDC.sol/MockUSDC.json'"));assert.equal(diagnostic.category,"serialization");assert.doesNotMatch(diagnostic.warning,/RPC is temporarily unavailable/i)});
