import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { DemoWalkthrough } from "../src/components/DemoWalkthrough.tsx";
import { buildDemoPresentation, nextDemoStage, normalizeDemoStage, previousDemoStage, restartDemo } from "../src/data/demo-stages.ts";
import { verifiedFallback } from "../src/lib/arc/read-core.ts";
import { isNavigationActive, navigation } from "../src/components/AppShell.tsx";
import { demo } from "../src/data/demo.ts";
import { OverviewView, JobsView, JobDetailsView, ProviderHistoryView } from "../src/components/live-pages.tsx";
import ProviderSelectionPage from "../app/provider-selection/page.tsx";
import ProviderDecisionPage from "../app/provider-decision/page.tsx";

const fallback=verifiedFallback("Arc RPC unavailable",new Date("2026-08-05T12:00:00Z"));
const live={...fallback,source:"LIVE" as const,rpcState:"Live" as const,warnings:[]};
const mismatch={...live,rpcState:"Data mismatch" as const,warnings:["Quality mismatch"]};
const presentation=buildDemoPresentation(fallback);
const render=(stage=1,data=presentation)=>renderToStaticMarkup(<DemoWalkthrough presentation={data} initialStage={stage}/>);
const source=()=>readFileSync("src/components/DemoWalkthrough.tsx","utf8");

test("Demo route renders Veriq Protocol Demo heading",()=>assert.match(render(),/Veriq Protocol Demo/));
test("Demo appears in main navigation",()=>assert.ok(navigation.some(item=>item.href==="/demo"&&item.label==="Demo")));
test("Demo route receives active-navigation state",()=>assert.equal(isNavigationActive("/demo","/demo"),true));
test("all eleven lifecycle stages exist in correct order",()=>assert.deepEqual(presentation.stages.map(s=>s.name),["Client policy","Provider selection","Provider decision","Job funded","Provider accepted","Result committed","Answers revealed","Exact-match scoring","Payout calculation","USDC settlement","Provider history"]));
test("Stage 1 is deterministic offchain policy",()=>assert.match(render(1),/Deterministic offchain policy/));
test("Stage 2 shows selected and rejected providers",()=>{const h=render(2);assert.match(h,/selected/);assert.match(h,/Rejected/)});
test("Stage 2 does not claim selection was onchain",()=>assert.match(render(2),/not read from the contract/));
test("Stage 3 renders ACCEPT and REJECT",()=>{const h=render(3);assert.match(h,/ACCEPT/);assert.match(h,/REJECT/)});
test("Stage 4 renders verified 1 USDC funded job",()=>assert.match(render(4),/Budget[\s\S]*1 USDC[\s\S]*Funded/));
test("Stage 5 renders provider acceptance",()=>assert.match(render(5),/Accepted funded Job #1/));
test("Stage 6 renders canonical commitment encoding",()=>assert.match(render(6),/keccak256\(abi\.encode\(answerHashes\)\)/));
test("Stage 7 renders 50-answer reveal requirements",()=>assert.match(render(7),/Exactly 50 hashes/));
test("Stage 8 renders 46 of 50 and 9200 bps",()=>{const h=render(8);assert.match(h,/46\/50/);assert.match(h,/9200/)});
test("Stage 9 renders 92 percent to 85 percent payout",()=>assert.match(render(9),/92% quality → 85% payout/));
test("Stage 10 renders 0.85 USDC provider payment",()=>assert.match(render(10),/Provider payment[\s\S]*0\.85 USDC/));
test("Stage 10 renders 0.15 USDC client refund",()=>assert.match(render(10),/Client refund[\s\S]*0\.15 USDC/));
test("Stage 10 renders zero escrow balance",()=>assert.match(render(10),/Escrow final balance[\s\S]*0 USDC/));
test("Stage 11 renders all provider-history counters",()=>{const h=render(11);for(const value of ["measuredJobs","cumulativeQualityBps","averageQualityBps","completedJobs","submissionDefaults"])assert.match(h,new RegExp(value))});
test("verified transaction references use Arc explorer",()=>assert.match(render(10),/https:\/\/testnet\.arcscan\.app\/tx\//));
test("transaction references are labeled verified static references",()=>assert.match(render(4),/Verified Milestone 13B transaction reference/));
test("live source state displays correctly",()=>assert.match(render(1,buildDemoPresentation(live)),/Live on Arc/));
test("verified fallback state displays correctly",()=>assert.match(render(),/Verified fallback/));
test("data mismatch state displays correctly",()=>assert.match(render(1,buildDemoPresentation(mismatch)),/Data mismatch/));
test("Previous cannot move before stage 1",()=>assert.equal(previousDemoStage(1),1));
test("Next cannot move after stage 11",()=>assert.equal(nextDemoStage(11),11));
test("Restart returns stage 1",()=>assert.equal(restartDemo(),1));
test("invalid stage safely returns stage 1",()=>{assert.equal(normalizeDemoStage(0),1);assert.equal(normalizeDemoStage("bad"),1)});
test("Demo controls perform no contract write",()=>assert.doesNotMatch(source(),/writeContract|sendTransaction|simulateContract/));
test("no wallet-connect control is rendered",()=>assert.doesNotMatch(render(),/connect wallet|walletconnect|metamask/i));
test("no signature request control is rendered",()=>assert.doesNotMatch(render(),/request signature|sign message/i));
test("no private-key input is rendered",()=>assert.doesNotMatch(render(),/private.?key|type="password"/i));
test("client demo source imports no wallet client",()=>assert.doesNotMatch(source(),/WalletClient|privateKeyToAccount/));
test("client demo source imports no write APIs",()=>assert.doesNotMatch(source(),/writeContract|sendTransaction/));
test("full headline remains visible on mobile",()=>assert.match(readFileSync("app/polish.css","utf8"),/\.demo-header h1[\s\S]*font-size: 42px/));
test("demo progress remains readable near 400px",()=>{const css=readFileSync("app/polish.css","utf8");assert.match(css,/\.demo-progress[\s\S]*overflow-x: auto/);assert.match(css,/\.demo-progress-step[\s\S]*flex-basis: 126px/)});
test("transaction hashes wrap without page overflow",()=>assert.match(readFileSync("app/polish.css","utf8"),/\.demo-transaction a[\s\S]*overflow-wrap: anywhere/));
test("statuses are not communicated by color alone",()=>assert.match(render(),/Completed/));
test("keyboard focus and current semantics exist",()=>{const h=render();assert.match(h,/aria-current="step"/);assert.match(source(),/ArrowLeft/);assert.match(source(),/ArrowRight/)});
test("reduced-motion support exists",()=>assert.match(readFileSync("app/polish.css","utf8"),/prefers-reduced-motion: reduce/));
test("existing live fallback model is reused",()=>{assert.match(readFileSync("app/demo/page.tsx","utf8"),/getArcReadState/);assert.doesNotMatch(source(),/createPublicClient|rpc\.testnet/)});
test("input fixtures are not mutated",()=>{const before=JSON.stringify(demo);buildDemoPresentation(fallback);assert.equal(JSON.stringify(demo),before)});
test("completion summary matches Job #1",()=>assert.deepEqual(presentation.conclusion.map(x=>x.value),["92%","85%","0.85 USDC","0.15 USDC","0 USDC","Updated","Settled"]));
test("all existing route views still render",()=>{for(const node of [<OverviewView/>,<JobsView/>,<JobDetailsView params={{id:"1"}}/>,<ProviderHistoryView/>,<ProviderSelectionPage/>,<ProviderDecisionPage/>])assert.ok(renderToStaticMarkup(node).length>400)});
test("provider fixture pages remain labeled offchain",()=>{assert.match(renderToStaticMarkup(<ProviderSelectionPage/>),/not onchain/);assert.match(renderToStaticMarkup(<ProviderDecisionPage/>),/not onchain/)});
test("Jobs 2 through 4 remain Static demo",()=>assert.ok((renderToStaticMarkup(<JobsView/>).match(/Static demo/g)??[]).length>=3));
