import assert from "node:assert/strict";
import test from "node:test";
import React from "react";
import { renderToStaticMarkup } from "react-dom/server";
import { readFileSync } from "node:fs";
import { OverviewView as OverviewPage, JobsView as JobsPage, JobDetailsView as JobDetailsPage, ProviderHistoryView as ProviderHistoryPage } from "../src/components/live-pages.tsx";
import ProviderSelectionPage from "../app/provider-selection/page.tsx";
import ProviderDecisionPage from "../app/provider-decision/page.tsx";
import { AppShell, navigation } from "../src/components/AppShell.tsx";
import { AddressDisplay, JobLifecycle, StatusBadge } from "../src/components/ui.tsx";
import { ProviderDecisionCard, ProviderHistoryCard } from "../src/components/providers.tsx";
import { demo } from "../src/data/demo.ts";
import { explorerLinks, formatAddress, formatBps } from "../src/lib/ui/format.ts";

const render=(node:React.ReactNode)=>renderToStaticMarkup(React.createElement(React.Fragment,null,node));
const overview=()=>render(React.createElement(OverviewPage));
const details=()=>render(React.createElement(JobDetailsPage,{params:{id:"1"}}));

test("overview renders the protocol headline",()=>assert.match(overview(),/Agents get paid for measured results\./));
test("overview route preserves sticky-header clearance at desktop and mobile widths",()=>{const page=readFileSync("app/page.tsx","utf8");const css=readFileSync("app/polish.css","utf8");assert.match(page,/className="overview-route"/);assert.match(css,/\.overview-route \.hero[\s\S]*padding-top: 56px[\s\S]*scroll-margin-top: 110px/);assert.match(css,/@media \(max-width: 720px\)[\s\S]*\.overview-route \.hero[\s\S]*padding-top: 36px[\s\S]*scroll-margin-top: 150px/);assert.match(overview(),/Agents get paid for measured results\.[\s\S]*Verified fallback/)});
test("overview renders Arc Testnet status",()=>assert.match(render(React.createElement(AppShell,null,React.createElement(OverviewPage))),/Arc Testnet/));
test("overview renders verified 92% quality",()=>assert.match(overview(),/Measured quality[\s\S]*92%/));
test("overview renders 85% payout",()=>assert.match(overview(),/Provider payout[\s\S]*85%/));
test("overview renders 0.15 USDC refund",()=>assert.match(overview(),/Client refund[\s\S]*0\.15 USDC/));
test("navigation includes every required section",()=>{const html=render(React.createElement(AppShell,null,"content"));for(const item of navigation)assert.match(html,new RegExp(item.label));assert.deepEqual(navigation.map(n=>n.label),["Overview","Demo","Jobs","Provider Selection","Provider Decision","Provider History","Execute"])});
test("Job #1 displays status Settled",()=>assert.match(render(React.createElement(JobsPage)),/Job #1[\s\S]*Settled/));
test("Job #1 displays budget 1 USDC",()=>assert.match(details(),/Budget[\s\S]*1 USDC/));
test("job details display 46\/50 answers",()=>assert.match(details(),/46\/50 answers/));
test("job details display qualityBps 9200 as 92%",()=>{const html=details();assert.match(html,/9200 bps = 92%/)});
test("job details display payoutBps 8500 as 85%",()=>assert.match(details(),/92% quality → 85% payout/));
test("job details display provider payment 0.85 USDC",()=>assert.match(details(),/Provider payment[\s\S]*0\.85 USDC/));
test("job details display client refund 0.15 USDC",()=>assert.match(details(),/Client refund[\s\S]*0\.15 USDC/));
test("job details display escrow balance zero",()=>assert.match(details(),/Escrow balance[\s\S]*0 USDC/));
test("lifecycle shows all completed steps in order",()=>{const html=render(React.createElement(JobLifecycle,{job:demo.verifiedJob}));const labels=["Funded","Accepted","Submitted","Scored","Settled"];let previous=-1;for(const label of labels){const current=html.indexOf(label);assert.ok(current>previous,`${label} must follow the preceding step`);previous=current}assert.equal((html.match(/timeline-marker/g)??[]).length,5)});
test("provider selection shows the winning provider",()=>{const html=render(React.createElement(ProviderSelectionPage));assert.match(html,/Selected provider/);assert.match(html,/0x1111…1111/)});
test("rejected providers display reasons",()=>{const html=render(React.createElement(ProviderSelectionPage));assert.match(html,/Rejected providers/);assert.match(html,/Task type is not supported\./)});
test("provider decision renders ACCEPT for profitable work",()=>{const html=render(React.createElement(ProviderDecisionCard,{example:demo.decisions[0]}));assert.match(html,/ACCEPT/);assert.match(html,/148\.00 USDC/)});
test("provider decision renders REJECT for the unprofitable fixture",()=>{const html=render(React.createElement(ProviderDecisionPage));assert.match(html,/Unprofitable fixture/);assert.match(html,/REJECT/);assert.match(html,/6\.80 USDC/)});
test("provider history displays all five counters",()=>{const html=render(React.createElement(ProviderHistoryCard,{history:demo.providerHistory}));for(const label of ["Measured jobs","Cumulative quality","Average quality","Completed jobs","Submission defaults"])assert.match(html,new RegExp(label))});
test("transaction links use the Arc explorer domain",()=>{for(const item of demo.verifiedJob.transactions)assert.ok(explorerLinks.transaction(item.hash).startsWith("https://testnet.arcscan.app/tx/"));assert.match(details(),/https:\/\/testnet\.arcscan\.app\/tx\//)});
test("address formatting does not alter the original underlying address",()=>{const original=demo.verifiedJob.provider;const shortened=formatAddress(original);assert.notEqual(shortened,original);assert.equal(demo.verifiedJob.provider,original);const html=render(React.createElement(AddressDisplay,{address:original}));assert.ok(html.includes(`data-address="${original}"`))});
test("status badges render text, not color alone",()=>{for(const status of ["Funded","Accepted","Submitted","Scored","Settled","Defaulted"] as const)assert.match(render(React.createElement(StatusBadge,{status})),new RegExp(`>${status}<`))});
test("mobile layout components render without missing content",()=>{const pages=[OverviewPage,JobsPage,ProviderSelectionPage,ProviderDecisionPage,ProviderHistoryPage];for(const Page of pages){const html=render(React.createElement(Page));assert.ok(html.length>500);assert.doesNotMatch(html,/undefined|null/)}const html=details();for(const value of ["Job #1","46/50 answers","0.85 USDC","0.15 USDC","Settlement complete"])assert.match(html,new RegExp(value.replace("/","\\/")))});
test("demo data contains no private-key-shaped fields",()=>{const visit=(value:unknown,path="demo")=>{if(!value||typeof value!=="object")return;for(const [key,child] of Object.entries(value)){assert.doesNotMatch(key,/private.?key|secret|mnemonic/i,`secret-shaped field at ${path}.${key}`);visit(child,`${path}.${key}`)}};visit(demo)});
test("formatting helpers do not mutate existing data objects",()=>{const before=JSON.stringify(demo);assert.equal(formatBps(demo.verifiedJob.qualityBps),"92%");assert.ok(formatAddress(demo.verifiedJob.client).includes("…"));assert.equal(JSON.stringify(demo),before);assert.ok(Object.isFrozen(demo));assert.ok(Object.isFrozen(demo.verifiedJob))});
