import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import React from"react";import{renderToStaticMarkup}from"react-dom/server";import type{Address}from"viem";import{PayoutPreviewDetails,formatUsdc}from"../src/components/PayoutCalculationStep";import{buildInteractiveJobParameters,buildProviderAnswerHashes,INTERACTIVE_PROVIDER_ADDRESS,INTERACTIVE_PROVIDER_COMMITMENT,type PersistedInteractiveJob}from"../src/lib/arc/interactive-job";import{calculateLivePayoutPreview,type PayoutPreviewReader,type PreviewLiveJob,type StoredSettlement}from"../src/lib/arc/readPayoutPreview";import{calculatePayoutUsdc,estimatePayoutBps,validateCurve}from"../src/lib/payout/estimatePayout";
const CLIENT="0x333C8bc19741f2Ed0C57d0C028Bff7c076B28E5C"as Address,PROVIDER=INTERACTIVE_PROVIDER_ADDRESS;
function state(jobId="4"):PersistedInteractiveJob{const p=buildInteractiveJobParameters(2_000_000_000n);return{version:1,chainId:5_042_002,jobId,client:CLIENT,provider:PROVIDER,createTransactionHash:`0x${"b".repeat(64)}`,taskSpecHash:p.taskSpecHash,canonicalizationVersionHash:p.canonicalizationVersionHash,metricPoints:p.metricPoints.map(String),payoutBps:p.payoutBps.map(String),acceptanceDeadline:p.acceptanceDeadline.toString(),submissionDeadline:p.submissionDeadline.toString(),revealDeadline:p.revealDeadline.toString(),expectedAnswerCommitment:p.expectedAnswerCommitment,expectedAnswerHashes:p.expectedAnswerHashes,budget:"1000000",status:"Scored",confirmedProvider:PROVIDER,providerAnswerHashes:buildProviderAnswerHashes(),providerResultCommitment:INTERACTIVE_PROVIDER_COMMITMENT,commitTransactionHash:null,answerCount:50,qualityBps:9200,revealTransactionHash:null}}
class Fake implements PayoutPreviewReader{ids:bigint[]=[];job:PreviewLiveJob={client:CLIENT,provider:PROVIDER,budget:1_000_000n,status:4};status=4;quality=9200n;metrics:readonly bigint[]=[7000n,9000n,9800n];payouts:readonly bigint[]=[0n,8000n,10000n];settlement:StoredSettlement={qualityBps:9200n,payoutBps:0n,providerPayment:0n,clientRefund:0n,status:4};track(id:bigint){this.ids.push(id)}async readJob(id:bigint){this.track(id);return this.job}async readStatus(id:bigint){this.track(id);return this.status}async readQualityBps(id:bigint){this.track(id);return this.quality}async readMetricPoints(id:bigint){this.track(id);return this.metrics}async readPayoutPoints(id:bigint){this.track(id);return this.payouts}async readSettlementResult(id:bigint){this.track(id);return this.settlement}}
test("dynamic active job ID drives every live read",async()=>{const f=new Fake();const result=await calculateLivePayoutPreview(f,state("47"));assert.equal(result.jobId,47n);assert.deepEqual(f.ids,[47n,47n,47n,47n,47n,47n])});
test("only Scored status is accepted",async()=>{for(const status of[1,2,3,5]){const f=new Fake();f.status=status;f.job={...f.job,status};f.settlement={...f.settlement,status};await assert.rejects(calculateLivePayoutPreview(f,state()),/no longer Scored/)}});
test("live quality and stored curve produce exact preview",async()=>{const result=await calculateLivePayoutPreview(new Fake(),state());assert.equal(result.qualityBps,9200);assert.deepEqual(result.metricPoints,[7000,9000,9800]);assert.deepEqual(result.payoutPoints,[0,8000,10000]);assert.equal(result.payoutBps,8500)});
test("one-USDC budget produces exact provider payment and refund",async()=>{const result=await calculateLivePayoutPreview(new Fake(),state());assert.equal(result.budget,1_000_000n);assert.equal(result.providerPayment,850_000n);assert.equal(result.clientRefund,150_000n);assert.equal(result.providerPayment+result.clientRefund,result.budget)});
test("payment floors first and refund receives remainder",()=>{const payment=calculatePayoutUsdc(3n,3333);assert.equal(payment,0n);assert.equal(3n-payment,3n);const another=calculatePayoutUsdc(10_001n,5000);assert.equal(another,5000n);assert.equal(10_001n-another,5001n)});
test("existing mirror preserves Solidity boundary behavior",()=>{const m=[7000,9000,9800],p=[0,8000,10000];assert.equal(estimatePayoutBps(m,p,6999),0);assert.equal(estimatePayoutBps(m,p,7000),0);assert.equal(estimatePayoutBps(m,p,9000),8000);assert.equal(estimatePayoutBps(m,p,9800),10000);assert.equal(estimatePayoutBps(m,p,10000),10000)});
test("invalid curve lengths are rejected",()=>{assert.throws(()=>validateCurve([1],[1]),/TooFew/);assert.throws(()=>validateCurve([1,2],[1]),/LengthMismatch/)});
test("invalid ordering and out-of-range curve values are rejected",()=>{assert.throws(()=>validateCurve([1,1],[0,1]),/MetricNotIncreasing/);assert.throws(()=>validateCurve([1,2],[2,1]),/PayoutNotNonDecreasing/);assert.throws(()=>validateCurve([1,10001],[0,1]),/ValueOutOfRange/);assert.throws(()=>validateCurve([1,2],[0,10001]),/ValueOutOfRange/)});
test("live curve must match the active interactive policy",async()=>{const a=new Fake();a.metrics=[7000n,9001n,9800n];await assert.rejects(calculateLivePayoutPreview(a,state()),/does not match/);const b=new Fake();b.payouts=[0n,8001n,10000n];await assert.rejects(calculateLivePayoutPreview(b,state()),/does not match/)});
test("pre-settlement stored payout payment and refund must remain zero",async()=>{for(const field of["payoutBps","providerPayment","clientRefund"]as const){const f=new Fake();f.settlement={...f.settlement,[field]:1n};await assert.rejects(calculateLivePayoutPreview(f,state()),/settlement values/)}});
test("party and budget mismatches are rejected",async()=>{const a=new Fake();a.job={...a.job,client:"0x2222222222222222222222222222222222222222"};await assert.rejects(calculateLivePayoutPreview(a,state()),/parties/);const b=new Fake();b.job={...b.job,budget:2_000_000n};await assert.rejects(calculateLivePayoutPreview(b,state()),/budget/)});
test("recovered Scored job recomputes rather than persisting preview",async()=>{const s=state(),result=await calculateLivePayoutPreview(new Fake(),s);assert.equal(result.status,"Ready to Settle");assert.equal("providerPayment"in s,false);assert.equal("clientRefund"in s,false)});
test("preview UI is explicit and makes no movement claim",async()=>{const preview=await calculateLivePayoutPreview(new Fake(),state());const html=renderToStaticMarkup(<><h2>Settlement Preview</h2><PayoutPreviewDetails preview={preview}/></>);assert.match(html,/Settlement Preview/);assert.match(html,/No funds move/);assert.match(html,/1\.000000 USDC/);assert.match(html,/85%/);assert.match(html,/0\.850000 USDC/);assert.match(html,/0\.150000 USDC/);assert.match(html,/Ready to Settle/);for(const claim of[/\bPaid\b/,/\bReceived\b/,/\bRefunded\b/,/Settlement complete/])assert.doesNotMatch(html,claim);assert.equal(formatUsdc(1n),"0.000001")});
test("Milestone 6 surface is read-only with no authorization path",()=>{const files=["src/lib/arc/abi/veriq-escrow-payout-preview.ts","src/lib/arc/readPayoutPreview.ts","src/components/PayoutCalculationStep.tsx"],source=files.map(file=>readFileSync(file,"utf8")).join("\n");assert.doesNotMatch(source,/createWalletClient|custom\(|writeContract|simulateContract|request\(|eth_requestAccounts|settle\(|transfer|approve|claim/);const abi=readFileSync(files[0],"utf8");assert.equal((abi.match(/stateMutability: "view"/g)??[]).length,6);assert.doesNotMatch(abi,/nonpayable|payable|event/)});
