import assert from"node:assert/strict";import{readFileSync}from"node:fs";import test from"node:test";import React from"react";import{renderToStaticMarkup}from"react-dom/server";import{encodeEventTopics,type Address,type Hash,type Hex}from"viem";
import{RevealScoreStep}from"../src/components/RevealScoreStep";import{veriqEscrowRevealAbi}from"../src/lib/arc/abi/veriq-escrow-reveal";import{buildInteractiveJobParameters,buildProviderAnswerHashes,INTERACTIVE_EXPECTED_COMMITMENT,INTERACTIVE_PROVIDER_ADDRESS,INTERACTIVE_PROVIDER_COMMITMENT,parsePersistedInteractiveJob,serializeInteractiveJob,type PersistedInteractiveJob}from"../src/lib/arc/interactive-job";import{commitAnswers}from"../src/lib/local-chain/answers";import{reconcileRecoveredJob}from"../src/lib/wallet/acceptFundedJob";import{createBrowserRevealAdapter,executeRevealAndScore,EXPECTED_QUALITY_BPS,REVEAL_SAFETY_BUFFER_SECONDS,verifyRevealFixtures,type RevealJob,type RevealScoreAdapter}from"../src/lib/wallet/revealAndScore";import type{InjectedProvider}from"../src/lib/wallet/injectedWallet";
const CLIENT="0x333C8bc19741f2Ed0C57d0C028Bff7c076B28E5C"as Address,PROVIDER=INTERACTIVE_PROVIDER_ADDRESS,OTHER="0x2222222222222222222222222222222222222222"as Address,HASH=`0x${"e".repeat(64)}`as Hash;
function state(jobId="47"):PersistedInteractiveJob{const p=buildInteractiveJobParameters(2_000_000_000n),provider=buildProviderAnswerHashes();return{version:1,chainId:5_042_002,jobId,client:CLIENT,provider:PROVIDER,createTransactionHash:`0x${"b".repeat(64)}`,taskSpecHash:p.taskSpecHash,canonicalizationVersionHash:p.canonicalizationVersionHash,metricPoints:p.metricPoints.map(String),payoutBps:p.payoutBps.map(String),acceptanceDeadline:p.acceptanceDeadline.toString(),submissionDeadline:p.submissionDeadline.toString(),revealDeadline:p.revealDeadline.toString(),expectedAnswerCommitment:p.expectedAnswerCommitment,expectedAnswerHashes:p.expectedAnswerHashes,budget:"1000000",status:"Submitted",confirmedProvider:PROVIDER,providerAnswerHashes:provider,providerResultCommitment:INTERACTIVE_PROVIDER_COMMITMENT,commitTransactionHash:null,answerCount:50}}
class Fake implements RevealScoreAdapter{now=2_000_000_000n;live:RevealJob={client:CLIENT,provider:PROVIDER,budget:1_000_000n,expectedAnswerCommitment:INTERACTIVE_EXPECTED_COMMITMENT,revealDeadline:this.now+10800n,status:3};result=INTERACTIVE_PROVIDER_COMMITMENT;quality=EXPECTED_QUALITY_BPS;status=4;event={jobId:47n,qualityBps:EXPECTED_QUALITY_BPS};writes=0;revalidations=0;failAt=0;writeError:Error|null=null;receiptFails=false;resultChanges=false;async revalidate(){this.revalidations++;if(this.revalidations===this.failAt)throw new Error("Wallet chain or account changed")};async readJob(){return this.live};async readResultCommitment(){return this.resultChanges&&this.writes>0?`0x${"1".repeat(64)}`as Hex:this.result};async readStatus(){return this.status};async readQualityBps(){return this.quality};async latestBlockTimestamp(){return this.now};async revealAndScore(_c:Address,id:bigint,expected:readonly Hex[],provider:readonly Hex[]){this.writes++;assert.equal(id,47n);assert.equal(expected.length,50);assert.equal(provider.length,50);if(this.writeError)throw this.writeError;return HASH};async waitForSuccessfulReceipt(){if(this.receiptFails)throw new Error("transaction reverted");return{logs:[]}}decodeJobScored(){return this.event}}
test("dynamic active job ID is used and successful scoring persists authoritative result",async()=>{const f=new Fake(),phases:string[]=[];const result=await executeRevealAndScore(f,state("47"),CLIENT,p=>phases.push(p));assert.equal(f.writes,1);assert.equal(f.revalidations,2);assert.equal(result.status,"Scored");assert.equal(result.qualityBps,9200);assert.equal(result.revealTransactionHash,HASH);assert.ok(phases.includes("confirming-score"));assert.deepEqual(parsePersistedInteractiveJob(serializeInteractiveJob(result)),result)});
test("client authorization blocks provider and unrelated wallets",async()=>{for(const wallet of[PROVIDER,OTHER]){const f=new Fake();await assert.rejects(executeRevealAndScore(f,state(),wallet),/job client/);assert.equal(f.writes,0)}});
test("Submitted status is required",async()=>{const f=new Fake();f.live.status=2;await assert.rejects(executeRevealAndScore(f,state(),CLIENT),/not Submitted/);assert.equal(f.writes,0)});
test("fixtures are exact 50-element ABI commitments with four deterministic mismatches",()=>{const s=state(),fixtures=verifyRevealFixtures(s);assert.equal(fixtures.expected.length,50);assert.equal(fixtures.provider.length,50);assert.equal(commitAnswers(fixtures.expected),INTERACTIVE_EXPECTED_COMMITMENT);assert.equal(commitAnswers(fixtures.provider),INTERACTIVE_PROVIDER_COMMITMENT);assert.deepEqual(fixtures.provider.slice(0,46),fixtures.expected.slice(0,46));assert.equal(fixtures.provider.slice(46).filter((v,i)=>v!==fixtures.expected[i+46]).length,4)});
test("wrong array length and altered order are rejected",()=>{const short={...state(),providerAnswerHashes:buildProviderAnswerHashes().slice(0,49)}as unknown as PersistedInteractiveJob;assert.throws(()=>verifyRevealFixtures(short),/exactly 50/);const reordered=[...buildProviderAnswerHashes()];[reordered[0],reordered[1]]=[reordered[1],reordered[0]];assert.throws(()=>verifyRevealFixtures({...state(),providerAnswerHashes:reordered}),/fixture|commitment/)});
test("on-chain expected and provider commitment mismatches prevent write",async()=>{const a=new Fake();a.live.expectedAnswerCommitment=`0x${"2".repeat(64)}`;await assert.rejects(executeRevealAndScore(a,state(),CLIENT),/Expected commitment/);const b=new Fake();b.result=`0x${"3".repeat(64)}`as Hex;await assert.rejects(executeRevealAndScore(b,state(),CLIENT),/Provider commitment/);assert.equal(a.writes+b.writes,0)});
test("reveal deadline and exact 60-second safety buffer prevent write",async()=>{for(const offset of[0n,REVEAL_SAFETY_BUFFER_SECONDS]){const f=new Fake();f.live.revealDeadline=f.now+offset;await assert.rejects(executeRevealAndScore(f,state(),CLIENT),/too close/);assert.equal(f.writes,0)}});
test("account or chain change on immediate revalidation prevents write",async()=>{const f=new Fake();f.failAt=2;await assert.rejects(executeRevealAndScore(f,state(),CLIENT),/changed/);assert.equal(f.writes,0)});
test("simulation failure, user rejection, and receipt failure propagate",async()=>{for(const message of["simulation failed","User rejected request 4001"]){const f=new Fake();f.writeError=new Error(message);await assert.rejects(executeRevealAndScore(f,state(),CLIENT),new RegExp(message.split(" ")[0],"i"))}const receipt=new Fake();receipt.receiptFails=true;await assert.rejects(executeRevealAndScore(receipt,state(),CLIENT),/reverted/)});
test("wrong JobScored event job or quality fails",async()=>{const a=new Fake();a.event={jobId:48n,qualityBps:EXPECTED_QUALITY_BPS};await assert.rejects(executeRevealAndScore(a,state(),CLIENT),/job ID mismatch/);const b=new Fake();b.event={jobId:47n,qualityBps:9100n};await assert.rejects(executeRevealAndScore(b,state(),CLIENT),/quality value mismatch/)});
test("Scored status, 9200 quality, and unchanged commitment are required on readback",async()=>{const a=new Fake();a.status=3;await assert.rejects(executeRevealAndScore(a,state(),CLIENT),/not confirmed Scored/);const b=new Fake();b.quality=9100n;await assert.rejects(executeRevealAndScore(b,state(),CLIENT),/score readback/);const c=new Fake();c.resultChanges=true;await assert.rejects(executeRevealAndScore(c,state(),CLIENT),/changed after scoring/)});
test("Scored recovery verifies quality and never fabricates reveal hash",()=>{const live={client:CLIENT,provider:PROVIDER,budget:1_000_000n,acceptanceDeadline:1n,status:4};assert.throws(()=>reconcileRecoveredJob(state(),live,INTERACTIVE_PROVIDER_COMMITMENT,9100n),/quality/);const recovered=reconcileRecoveredJob(state(),live,INTERACTIVE_PROVIDER_COMMITMENT,9200n);assert.equal(recovered.status,"Scored");assert.equal(recovered.qualityBps,9200);assert.equal(recovered.revealTransactionHash,null);assert.equal(recovered.providerAnswerHashes?.length,50)});
test("JobScored browser decoder verifies indexed job and quality",()=>{const adapter=createBrowserRevealAdapter({request:async()=>null}as unknown as InjectedProvider);const topics=encodeEventTopics({abi:veriqEscrowRevealAbi,eventName:"JobScored",args:{jobId:47n}});const data=`0x${EXPECTED_QUALITY_BPS.toString(16).padStart(64,"0")}`as Hex;assert.deepEqual(adapter.decodeJobScored([{data,topics:topics as readonly Hex[]}]),{jobId:47n,qualityBps:EXPECTED_QUALITY_BPS})});
test("client, provider, unrelated, and recovered Scored UI states are explicit",()=>{const p={request:async()=>null}as unknown as InjectedProvider;const client=renderToStaticMarkup(<RevealScoreStep account={CLIENT} provider={p} job={state()} onScored={()=>{}}/>);assert.match(client,/Validating submitted job/);assert.match(readFileSync("src/components/RevealScoreStep.tsx","utf8"),/Reveal &amp; Score|Reveal & Score/);const provider=renderToStaticMarkup(<RevealScoreStep account={PROVIDER} provider={p} job={state()} onScored={()=>{}}/>);assert.match(provider,/Switch to the client wallet/);assert.doesNotMatch(provider,/>Reveal &amp; Score</);const other=renderToStaticMarkup(<RevealScoreStep account={OTHER} provider={p} job={state()} onScored={()=>{}}/>);assert.match(other,/does not match/);const scored=reconcileRecoveredJob(state(),{client:CLIENT,provider:PROVIDER,budget:1_000_000n,acceptanceDeadline:1n,status:4},INTERACTIVE_PROVIDER_COMMITMENT,9200n);const html=renderToStaticMarkup(<RevealScoreStep account={CLIENT} provider={p} job={scored} onScored={()=>{}}/>);assert.match(html,/Scored/);assert.match(html,/92%/);assert.match(html,/9200/);assert.match(html,/Unavailable/);assert.match(html,/Confirmed on Arc/)});
test("Milestone 5 ABI exposes only reveal write and no settlement functionality",()=>{const abi=readFileSync("src/lib/arc/abi/veriq-escrow-reveal.ts","utf8"),wallet=readFileSync("src/lib/wallet/revealAndScore.ts","utf8"),source=abi+wallet;assert.match(abi,/name: "revealAndScore"/);assert.doesNotMatch(source,/name: "settle"|ProviderHistory|JobSettled|claimClientRevealDefault/);assert.equal((wallet.match(/writeContract/g)??[]).length,1)});
